### ISSUE TITLE
Error launching any .launch file

### ISSUE THREAD

**Issue by carlosmprocha** [miguelriemoliveira/psr_21-22#58]
Good night teacher @miguelriemoliveira , I was able to run all launch files without problem until I cloned a group repository. Since then for any .launch file, mine or shared, the following error appears: 

Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/__init__.py", line 258, in main
    args = rlutil.resolve_launch_arguments(args)
  File "/opt/ros/noetic/lib/python3/dist-packages/roslaunch/rlutil.py", line 92, in resolve_launch_arguments
    resolved = roslib.packages.find_resource(args[0], args[1])
  File "/opt/ros/noetic/lib/python3/dist-packages/roslib/packages.py", line 519, in find_resource
    pkg_path = rospack.get_path(pkg)
  File "/usr/lib/python3/dist-packages/rospkg/rospack.py", line 205, in get_path
    self._update_location_cache()
  File "/usr/lib/python3/dist-packages/rospkg/rospack.py", line 188, in _update_location_cache
    list_by_path(self._manifest_name, path, cache)
  File "/usr/lib/python3/dist-packages/rospkg/rospack.py", line 71, in list_by_path
    root = ElementTree(None, os.path.join(d, PACKAGE_FILE))
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 555, in __init__
    self.parse(file)
  File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 595, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: no element found: line 1, column 0

**Comment by carlosmprocha** [comment]
Sorry about this, apparently by deleting and cloning again the problem was fixed. 
I'm pretty sure I tried this before but it wasn't working.
Unfortunate, as I was curious about what was causing the problem.

Thank you for your time.

**Comment by miguelriemoliveira** [comment]
The good thing is that its working!
